language: node_js
node_js:
- 7
- 6
- 4

before_script: cd web

deploy:
  provider: heroku
  api_key:
    secure: a8lLCrxYwM8mEcanIxfQ5xzm0ZLljoeDTL3PKpyc73oHTf+vbZ4YeK46q3y1PTpwd4+18+eqLLHjwod9Z9NzGxplBVFGL8gnZ0iw31/joYAnvEThRZL17hGQFvsI+xAWG/abGxGJNECyWBhqQHGXRoXKk/LVDNFuK/C4ZYS97a67LYCt+6ThpzFdoMM8CEo55cYscSaaiFHK/m8nJ3M8RMGV+T3paZ8eWm3aLWJrFcxNu7jiMYMRqFFr6DkcuTJPqSLz82CnthlZZkll1+JVtXF+0NBhagsSvlVtTBiHjua69kzFGM5ELgFaqiVhSwuF++jE9PMxy4Z/BEDNid3dwIzpuHJ+lvHRV2pbT9RAFwoU81wXewlqGoVit+ZKDWlWWM7WA1qhGM0bpOL31YEQuMvBFyJ/2MMTYaIiI9rXlq7YJPlkKBbvJOoU7R2epBiuImpLP2qXoLaEamq+PAgmKzcTNwoJnUesjOZvs34q/XU+Lf7gSJMTiMI3ldIjHYuniR3BDNHP40zvQI4O4Ec6nMUpjnLzZbGUe71BtvgWzKNHquu3Pxw/g6OMyrMpO/e3jV8QW+ub8tc9Itt4/0tZHnqqoZW++COB4Sx67LOUxmGhazOrjUAzc3WQLdNImfys+FbwItiQm7AWg38qpFrfRyEz+suDDQB34W/R2DcfUZo=
