/*
 * This is a demo component the Eletrode app generator included
 * to show using Skeleton CSS lib (named base.css) and Redux
 * store for display HTML elements and managing states.
 *
 * To start your own app, please replace or remove these files:
 *
 * - this file (home.jsx)
 * - demo-buttons.jsx
 * - demo-pure-states.jsx
 * - demo-states.jsx
 * - reducers/index.jsx
 * - styles/*.css
 *
 */

import React from 'react';
import custom from '../styles/custom.css';
import electrodePng from '../images/electrode.png';
import DemoStates from './demo-states';
import DemoPureStates from './demo-pure-states';
import { DemoButtons } from './demo-buttons';
import nav from './nav';
import { Button, Header, Segment } from 'semantic-ui-react'
import Payments from './payments';

const ButtonExampleButton = () => (
      <Button>
        Click Here (generated by semantic)
      </Button>
)
/**/

export default () =>
  (<div className={custom.container}>
    {/**/}

    <section className={custom.header}>
      <Header>
        Hello from {' '}
        <a href="https://github.com/electrode-io">{'Electrode'} <img src={electrodePng} /></a>
      </Header>
      <ButtonExampleButton />
    </section>

    <Segment>
      <DemoStates />
    </Segment>

    <Segment>
      <DemoPureStates />
    </Segment>

    <Segment>
      <DemoButtons />
    </Segment>
  </div>);
